export const seedAgents = [
  {
    agent_id: "agent-product-manager",
    display_name: "Product Manager",
    summary: "定义产品定位、用户价值、MVP 范围和优先级。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-product-manager:v1",
    capabilities: ["产品定位", "MVP 范围", "需求优先级", "用户价值"],
    boundaries: ["不负责代码实现", "不替代安全或隐私评审"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-ux-architect",
    display_name: "UX Architect",
    summary: "设计任务路径、信息架构、状态可见性和用户介入点。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-ux-architect:v1",
    capabilities: ["用户路径", "信息架构", "交互状态", "可用性"],
    boundaries: ["不负责视觉定稿", "不替代产品决策"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-ui-designer",
    display_name: "UI Designer",
    summary: "设计界面层级、视觉方向、组件状态和可读性。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-ui-designer:v1",
    capabilities: ["界面设计", "视觉层级", "组件状态", "响应式布局"],
    boundaries: ["不决定业务规则", "不负责后端架构"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-workflow-architect",
    display_name: "Workflow Architect",
    summary: "把复杂工作拆成状态机、阶段门禁和可追踪事件。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-workflow-architect:v1",
    capabilities: ["工作流", "状态机", "阶段门禁", "异常处理"],
    boundaries: ["不替代业务负责人确认优先级"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-multi-agent-architect",
    display_name: "Multi-Agent Systems Architect",
    summary: "设计多 Agent 编排、上下文隔离、质疑机制和失败恢复。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-multi-agent-architect:v1",
    capabilities: ["多 Agent 编排", "上下文治理", "质疑机制", "失败恢复"],
    boundaries: ["不直接处理 UI 细节"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-software-architect",
    display_name: "Software Architect",
    summary: "设计前后端分离、数据模型、服务边界和部署结构。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-software-architect:v1",
    capabilities: ["软件架构", "API", "数据模型", "部署"],
    boundaries: ["不替代安全审计"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-security-architect",
    display_name: "Security Architect",
    summary: "识别权限、密钥、文件、网络、部署和越权风险。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-security-architect:v1",
    capabilities: ["安全架构", "权限", "密钥管理", "部署安全"],
    boundaries: ["不提供最终合规法律意见"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-data-privacy-officer",
    display_name: "Data Privacy Officer",
    summary: "审视用户材料、个人信息、共享 Agent 和数据保留边界。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-data-privacy-officer:v1",
    capabilities: ["隐私", "数据最小化", "共享边界", "删除导出"],
    boundaries: ["不替代正式法务意见"],
    permissions: ["problem_only", "summary_only"]
  },
  {
    agent_id: "agent-identity-trust-architect",
    display_name: "Agentic Identity & Trust Architect",
    summary: "设计 Agent 身份、版本、信任、归属和共享发布规则。",
    agent_class: "system_public",
    owner_user_id: null,
    trust_status: "official_verified",
    visibility_scope: "all_users",
    publish_status: "published",
    default_pool_eligible: true,
    current_version_id: "agent-identity-trust-architect:v1",
    capabilities: ["Agent 身份", "版本", "信任状态", "共享治理"],
    boundaries: ["不负责底层模型能力评估"],
    permissions: ["problem_only", "summary_only"]
  }
];

export function createAgentVersion(agent) {
  return {
    agent_version_id: agent.current_version_id,
    agent_id: agent.agent_id,
    version_label: "v1",
    content_hash: `${agent.agent_id}:seed`,
    source_hash: "seed",
    source_type: "seed",
    instructions_snapshot: agent.summary,
    metadata_snapshot: {
      capabilities: agent.capabilities,
      boundaries: agent.boundaries
    },
    release_status: "active",
    created_at: new Date().toISOString()
  };
}
